version: "3.8"

services:
  base_image: 
    build:
      context: ../../
      dockerfile: docker/lsk/Dockerfile
    image: avt-lee:latest
    command: ["/bin/true"]

  ship_eo_service:
    <<: *base-service
    container_name: avt_ship_eo_detection
    command: python cli_lsk.py

  ship_sar_service:
    <<: *base-service
    container_name: avt_ship_sar_detection
    command: python cli_lsk_sar.py

  change_service:
    <<: *base-service
    container_name: avt_change_detection
    command: python cli_change.py


x-base-service: &base-service
  image: avt-lee:latest
  volumes:
    - ../../:/workspace/avt-detection-source
    - ../../../data/:/workspace/data
  environment:
    - NVIDIA_VISIBLE_DEVICES=all # Ensure all GPUs are accessible
  shm_size: '8g'
  container_name: lsk-base
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]

  working_dir: /workspace/avt-detection
